import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import TopScroll from "@/components/TopScroll";
import type { Metadata } from "next";
import { Jost, Rubik } from "next/font/google";
import "./globals.css";

const rubik = Rubik({ subsets: ["latin"] });
const jost = Jost({ subsets: ["latin"], variable: "--jost" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${rubik.className} ${jost.variable}`}>
        <Navbar />
        {children}
        <Footer />
        <TopScroll />
      </body>
    </html>
  );
}
